name: Export Pluto notebooks
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: pluto-export
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Install cowsay and figlet
        run: |
          sudo apt-get update
          sudo apt-get install -y cowsay figlet

      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: "1"

      - name: Cache Julia artifacts & such
        uses: julia-actions/cache@v1
        with:
          cache-registries: "true"

      - name: Set up notebook state cache
        uses: actions/cache@v3
        with:
          path: pluto_state_cache
          key: ${{ runner.os }}-pluto_state_cache-v2-${{ hashFiles('**/Project.toml', '**/Manifest.toml', '.github/workflows/*' ) }}-${{ hashFiles('**/*jl') }}
          restore-keys: |
            ${{ runner.os }}-pluto_state_cache-v2-${{ hashFiles('**/Project.toml', '**/Manifest.toml', '.github/workflows/*' ) }}

      - name: Run & export Pluto notebooks
        run:  |
          julia -e 'using Pkg
            Pkg.activate(mktempdir())
            Pkg.add([
              Pkg.PackageSpec(name="PlutoSliderServer", version="0.3.2-0.3"),
            ])

            import PlutoSliderServer

            PlutoSliderServer.github_action(".";
              Export_cache_dir="pluto_state_cache",
              Export_baked_notebookfile=false,
              Export_baked_state=false,
              # more parameters can go here
            )'

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: .
          single-commit: true
